version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restaurantDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./restaurant-backend/app
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:password@postgres/restaurantDB
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  # frontend:
  #   build:
  #     context: ./restaurant-frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4200:4200"
  #   depends_on:
  #     - backend

volumes:
  postgres-data:
