# # Use a Node.js base image
# FROM node:12

# # Set the working directory
# WORKDIR /usr/src/app

# # Install Ember CLI globally
# RUN npm install -g ember-cli

# # Install dependencies
# COPY package*.json ./
# RUN npm install

# # Copy the rest of the frontend codebase into the image
# COPY . .

# # Expose port 4200 for the Ember server
# EXPOSE 4200

# # Start the Ember server
# CMD ["ember", "serve", "--live-reload", "--host", "0.0.0.0"]
